blogtest/urls.py
from django.conf.urls import url
from django.contrib import admin
from app01 import views
from app02 import views2

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^login.html$', views.login),
    url(r'^reg.html$', views.reg),
    url(r'^all/(?P<type_id>\d+)/', views.index),
    url(r'^check_code/', views.check_code),
    url(r'^up_img/', views.up_img),

    url(r'^seek/', views2.seek),

    url(r'^logout/', views.logout),
    url(r'^add_up/', views.add_up),
    url(r'^comment/', views.comment),
    url(r'^check_comment/', views.check_comment),
    url(r'^del_comment/', views.del_comment),
    url(r'^control.html$', views.control),
    url(r'^upload_img.html$', views.upload_img),
    url(r'^add_article.html$', views.add_article),
    url(r'^article_manage/(?P<article_type_id>\d+)-(?P<category_id>\d+)-(?P<tags__nid>\d+).html$', views.article_manage),


    url(r'^(?P<site>\w+)/p/(?P<nid>\d+).html$', views.page),
    url(r'^(?P<site>\w+)/(?P<family>\w+)/(?P<nid>\d+-?\d*).html$', views.user),

    url(r'^index.html', views.index),

    url(r'^(?P<site>\w+).html$', views.user),

    url(r'', views.me),
]

app01/models.py
from django.db import models


class UserInfo(models.Model):
    """
    用户表
    """
    nid = models.BigAutoField(primary_key=True)
    username = models.CharField(verbose_name='用户名', max_length=32, unique=True)
    password = models.CharField(verbose_name='密码', max_length=64)
    nickname = models.CharField(verbose_name='昵称', max_length=32)
    email = models.EmailField(verbose_name='邮箱', unique=True)
    avatar = models.ImageField(verbose_name='头像')

    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    fans = models.ManyToManyField(verbose_name='粉丝们',
                                  to='UserInfo',
                                  through='UserFans',
                                  related_name='f',
                                  through_fields=('user', 'follower'))


class Blog(models.Model):
    """
    博客信息
    """
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site = models.CharField(verbose_name='个人博客前缀', max_length=32, unique=True)
    theme = models.CharField(verbose_name='博客主题', max_length=32)
    user = models.OneToOneField(to='UserInfo',
                                to_field='nid',
                                on_delete=models.CASCADE,)


class UserFans(models.Model):
    """
    互粉关系表
    """
    user = models.ForeignKey(verbose_name='博主', to='UserInfo', to_field='nid', related_name='users',on_delete=models.CASCADE,)
    follower = models.ForeignKey(verbose_name='粉丝', to='UserInfo', to_field='nid',on_delete=models.CASCADE, related_name='followers')

    class Meta:
        unique_together = [
            ('user', 'follower'),
        ]


class Category(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)

    blog = models.ForeignKey(verbose_name='所属博客', to='Blog',on_delete=models.CASCADE, to_field='nid')


class ArticleDetail(models.Model):
    """
    文章详细表
    """
    content = models.TextField(verbose_name='文章内容', )

    article = models.OneToOneField(verbose_name='所属文章', to='Article', to_field='nid',on_delete=models.CASCADE,)


class UpDown(models.Model):
    """
    文章顶或踩
    """
    article = models.ForeignKey(verbose_name='文章', to='Article', to_field='nid',on_delete=models.CASCADE,)
    user = models.ForeignKey(verbose_name='赞或踩用户', to='UserInfo', to_field='nid',on_delete=models.CASCADE,)
    up = models.BooleanField(verbose_name='是否赞')

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]


class Comment(models.Model):
    """
    评论表
    """
    nid = models.BigAutoField(primary_key=True)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    reply = models.ForeignKey(verbose_name='回复评论', to='self',on_delete=models.CASCADE, related_name='back', null=True)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid',on_delete=models.CASCADE,)
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid',on_delete=models.CASCADE,)


class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog',on_delete=models.CASCADE, to_field='nid')


class Article(models.Model):
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='文章标题', max_length=128)
    summary = models.CharField(verbose_name='文章简介', max_length=255)
    read_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid',on_delete=models.CASCADE,)
    category = models.ForeignKey(verbose_name='文章类型', to='Category',on_delete=models.CASCADE, to_field='nid', null=True)

    type_choices = [
        (1, "Python"),
        (2, "Linux"),
        (3, "OpenStack"),
        (4, "GoLang"),
    ]

    article_type_id = models.IntegerField(choices=type_choices, default=None)

    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )


class Article2Tag(models.Model):
    article = models.ForeignKey(verbose_name='文章', to="Article",on_delete=models.CASCADE, to_field='nid')
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid',on_delete=models.CASCADE,)

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]


templates/add_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <script src="/static/kindeditor-4.1.10/kindeditor-all.js"></script>
</head>
<body>
    <div style="width: 1060px;margin: 50px">
        <form action="/add_article.html"  class="form-horizontal" method="POST" novalidate>
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">文章标题</label>
                {{ obj.title }}
            </div>
                <div class="form-group">
                <label for="exampleInputEmail1">文章简介</label>
                {{ obj.summary }}
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">文章正文</label>
                {{ obj.content }}
            </div>
            <div class="form-group">
                <p>文章分类</p>
                {{ obj.article_type_id }}
            </div>
            <div class="form-group">
                <p>个人分类</p>
                {{ obj.category_id }}
            </div>
            <div class="form-group">
                <p>个人标签</p>
                {{ obj.tags_id }}
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <input type="submit" class="btn btn-default" value="保存">
                </div>
            </div>
        </form>
    </div>

    <script>
         KindEditor.create("#c1",{
            width: "1000px",
            height: "400px",
            resizeType:1,
            uploadJson: '/upload_img.html',
            extraFileUploadParams:{
                "csrfmiddlewaretoken":"{{ csrf_token }}"
            }
        })
    </script>
</body>
</html>

templates/article_manage.html
{% extends 'layout.html' %}
{% block css %}
    <style>
        .header-nav ul{
            margin: 5px 0;
        }
    </style>

{% endblock %}


{% block html %}
    <ol class="breadcrumb">
      <li><a href="#">文章管理</a></li>
      <li><a href="#" class="active">文章列表</a></li>
    </ol>
    <div style="padding: 10px 30px;border: 1px dashed #ccc">搜索条件</div>
    <div style="margin-left: 50px" class="header-nav">
        <ul class="nav nav-pills">
            {% if res.article_type_id == 0 %}
                <li role="presentation" class="active">
                  <a href="/article_manage/0-{{ res.category_id }}-{{ res.tags__nid }}.html">全部</a>
              </li>
            {% else %}
                <li role="presentation" >
                  <a href="/article_manage/0-{{ res.category_id }}-{{ res.tags__nid }}.html">全部</a>
                </li>
            {% endif %}
          {% for type in type_list %}
              {% if type.0 == res.article_type_id %}
                  <li role="presentation" class="active">
                    <a href="/article_manage/{{ type.0 }}-{{ res.category_id }}-{{ res.tags__nid }}.html">{{ type.1 }}</a>
                  </li>
              {% else %}
                  <li role="presentation">
                    <a href="/article_manage/{{ type.0 }}-{{ res.category_id }}-{{ res.tags__nid }}.html">{{ type.1 }}</a>
                  </li>
              {% endif %}
          {% endfor %}
        </ul>
        <ul class="nav nav-pills">
            {% if res.category_id == 0 %}
                <li role="presentation" class="active">
                  <a href="/article_manage/{{ res.article_type_id }}-0-{{ res.tags__nid }}.html">全部</a>
              </li>
            {% else %}
                <li role="presentation" >
                  <a href="/article_manage/{{ res.article_type_id }}-0-{{ res.tags__nid }}.html">全部</a>
                </li>
            {% endif %}
          {% for category in category_list %}
              {% if category.nid == res.category_id %}
                  <li role="presentation" class="active">
                    <a href="/article_manage/{{ res.article_type_id }}-{{ category.nid }}-{{ res.tags__nid }}.html">{{ category.title }}</a>
                  </li>
              {% else %}
                  <li role="presentation">
                    <a href="/article_manage/{{ res.article_type_id }}-{{ category.nid }}-{{ res.tags__nid }}.html">{{ category.title }}</a>
                  </li>
              {% endif %}
          {% endfor %}
        </ul>
        <ul class="nav nav-pills">
          {% if res.tags__nid == 0 %}
              <li role="presentation" class="active">
                <a href="/article_manage/{{ res.article_type_id }}-{{ res.category_id }}-0.html">全部</a>
              </li>
          {% else %}
              <li role="presentation">
                <a href="/article_manage/{{ res.article_type_id }}-{{ res.category_id }}-0.html">全部</a>
              </li>
          {% endif %}
          {% for tag in tag_list %}
              {% if tag.nid == res.tags__nid %}
                <li role="presentation" class="active">
                    <a href="/article_manage/{{ res.article_type_id }}-{{ res.category_id }}-{{ tag.nid }}.html">{{ tag.title }}</a>
                </li>
              {% else %}
                <li role="presentation">
                    <a href="/article_manage/{{ res.article_type_id }}-{{ res.category_id }}-{{ tag.nid }}.html">{{ tag.title }}</a>
                </li>
              {% endif %}
          {% endfor %}
        </ul>
    </div>
    <div>
        <div style="height: 36px;background-color: #ddd;line-height: 36px;border-bottom: 1px solid #9d9d9d;">
            搜索文章({{ obj_count }}篇)
            <a href="/add_article.html" style="float: right"><button type="button" class="btn btn-success">创建新文章</button></a>
        </div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th><strong>文章标题</strong></th>
                    <th><strong>操作</strong></th>
                </tr>
            </thead>
            <tbody>
                {% for foo in obj %}
                <tr>

                    <td><a href="/{{ foo.blog.site }}/p/{{ foo.nid }}.html">{{ foo.title }}</a></td>
                    <td>
                         <a href=""><button type="button" class="btn btn-danger">删除</button></a>
                         <a href=""><button type="button" class="btn btn-info">编辑</button></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <ul class="pagination">
            {{ page_info.pager|safe }}
    </ul>

{% endblock %}

templates/control.html
{% extends 'layout.html' %}

{% block html %}

    <h3>欢迎来到后台管理！</h3>

{% endblock %}

templates/home.html
{% extends 'user.html' %}

{% block css %}
<style>
    .content{
        position: absolute;
        left: 300px;
        right: 0;
        top: 60px;
        bottom: 0;
        min-width: 990px;
        overflow: scroll;
        z-index: 99;
}
    .b-text{
        margin-top: 30px;
        margin-bottom: 10px;
        border-bottom: 1px dashed #E8E7D0;
}
</style>
{% endblock %}

{% block html %}


{% for row in obj %}
    <div class="b-text" style="margin-top: 10px;">
        <div><a href="/{{ blog_msg.site }}/p/{{ row.nid }}.html">{{ row.title }}</a> </div>
        <div style="line-height: 30px">{{ row.summary }}</div>
        <div style="margin-bottom: 10px">
            {{ row.create_time|date:"Y-m-d H:i:s" }}
            <span>阅读({{ row.read_count }})</span>
            <span><a href="">评论({{ row.comment_count }})</a></span>
            <span><a href="">编辑</a></span>
        </div>
    </div>

{% endfor %}
    <nav aria-label="Page navigation">
            <ul class="pagination">
                {{ page_info.pager|safe }}
            </ul>
    </nav>

{% endblock %}

{% block script %}

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/font-awesome-4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="/static/css/index.css">
    <style>
        .sm-avatar{
            display: inline-block;
            position: relative;
            right: 85px;
            top: 10px;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top " >
  <div class="container-fluid col-md-offset-1 col-md-10">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">帅气的博客</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      {% if type_id %}
        <li><a href="/">全部 <span class="sr-only">(current)</span></a></li>
      {% else %}
        <li class="active"><a href="/">全部 <span class="sr-only">(current)</span></a></li>
      {% endif %}
          {% for row in tag  %}
              {% if row.0 == type_id %}
              <li class="active"><a href="/all/{{ row.0 }}/">{{ row.1 }}</a></li>
              {% else %}
              <li><a href="/all/{{ row.0 }}/">{{ row.1 }}</a></li>
              {% endif %}
          {% endfor %}
      </ul>
      <ul class="nav navbar-nav navbar-right" style="margin-right: 0px">
          {% if userinfo == None %}
            <li><a href="/reg.html">注册</a></li>
            <li><a href="/login.html">登录</a></li>
          {% else %}
            <li style="margin-right: 20px"><a href="/control.html">{{ userinfo.nickname }}</a></li>
           <div class="sm-avatar">
               <img src="/{{ userinfo.avatar }}" alt="" style="width: 30px;height: 30px">
           </div>
            <li><a href="/logout/">注销</a></li>
          {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
    <div class="col-md-10"></div><!-- /.container-fluid -->
</nav>

    <div class="col-md-offset-1 col-md-10 my_outer ">
        <div class="col-md-8 my_content" >
            {% for row in user_list %}
            <div class="my_content" >
                <div class="my_ati">
                    <div class="my_title"><a href="/{{ row.blog.site }}/p/{{ row.nid }}.html">{{ row.title }}</a> </div>
                    <div style="height: 80px;position: relative">
                        <div class="my_avatar">
                            <img src="/{{ row.blog.user.avatar }}" alt="" style="width: 76px;height: 76px">
                        </div>
                        <div style="margin-left: 20px">
                            {{ row.summary }}
                        </div>
                    </div>
                    <div class="ati_bottom">
                        <a href="/{{ row.blog.site }}.html"><i class="fa fa-user-o" aria-hidden="true"></i>
                        {{ row.blog.user.nickname }}</a>
                        <span>发布于</span>
                        <span class="aticle_time">{{ row.create_time|date:"Y-m-d H:i:s" }}</span>
                        <a href="" class="my_active">
                            <i class="fa fa-commenting-o" aria-hidden="true"></i>
                            <span>{{ row.comment_count }}</span>
                        </a>
                        <a href="" class="my_active">
                            <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                            <span>{{ row.up_count }}</span>
                        </a>

                    </div>
                </div>
            </div>
            {% endfor %}
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {{ page_info.pager|safe }}
            </ul>
        </nav>
        </div>

        <div class="col-md-4 my_text" style="float: right">
            <div class="list-group">
              <a href="#" class="list-group-item disabled">
                吐血推荐
              </a>
              <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
              <a href="#" class="list-group-item">Morbi leo risus</a>
              <a href="#" class="list-group-item">Porta ac consectetur ac</a>
              <a href="#" class="list-group-item">Vestibulum at eros</a>
            </div>
            <div class="list-group">
              <a href="#" class="list-group-item disabled">
                评论最多
              </a>
              <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
              <a href="#" class="list-group-item">Morbi leo risus</a>
              <a href="#" class="list-group-item">Porta ac consectetur ac</a>
              <a href="#" class="list-group-item">Vestibulum at eros</a>
            </div>
        </div>
    </div>

</body>
</html>

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="/static/jquery-3.2.1.js">
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/font-awesome-4.7.0/css/font-awesome.css" />
    <link rel="stylesheet" href="/static/css/commons.css" />
    {% block css %}{% endblock %}
</head>
<body>
    <div class="pg-header">
        <div class="logo left">葫芦娃后台管理</div>
        <div class="avatar right" style="position: relative">
            <img style="width: 40px;height: 40px;" src="/static/img/timg.jpg">
            <div class="user-info">
                <a>个人资料</a>
                <a>注销</a>
            </div>
        </div>
        <div class="rmenus right">
            {% if blog.site %}
                <a href="/{{ blog.site }}.html" style="float: left!important;"><i class="fa fa-commenting-o" aria-hidden="true"></i> 博客首页</a>
            {% else %}
                <a id="apply-tip" style="float: left!important;"><i class="fa fa-commenting-o" aria-hidden="true"></i> 博客首页</a>
            {% endif %}
            <a><i class="fa fa-commenting-o" aria-hidden="true"></i> 消息</a>
            <a><i class="fa fa-envelope-o" aria-hidden="true"></i> 邮件</a>
        </div>
    </div>
    <div class="pg-body">
        <div class="menus">
            <a href="/article_manage/0-0-0.html"><i class="fa fa-futbol-o" aria-hidden="true"></i> 文章管理</a>
            <a href="#"><i class="fa fa-futbol-o " aria-hidden="true"></i> 开通博客</a>
            <a><i class="fa fa-futbol-o" aria-hidden="true"></i> 分类管理</a>
            <a><i class="fa fa-futbol-o" aria-hidden="true"></i> 标签管理</a>
            <a><i class="fa fa-futbol-o" aria-hidden="true"></i> 个人信息</a>
        </div>
        <div class="content">

            {% block html  %}{% endblock %}

        </div>
    </div>
    {% block js %}{% endblock %}
    <script type="text/javascript" src="/static/jquery-3.2.1.js"></script>
    <script>
        $('#apply-tip').click(function () {
            alert("请先开通博客！");
        })
    </script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body{
            background-color: #fbfbfb;
        }
        .yan{
            position: absolute;
            right: 200px;
            top: 220px;
        }
        .page-header{
            background-color: white;
            border-bottom: 1px solid #ffa5c7;
        }
        .left img{
            position: relative;
            left: 100px;
            width: 390px;
            height: 300px;
        }
    </style>
</head>
<body>
    <div class="col-xs-12" style="height: 220px">
        <div class="page-header"></div>
    </div>
    <div class="outer">
        <div class="left" style="display: inline-block">
            <img src="/static/img/login.jpg">
        </div>
        <div class="col-xs-4 yan">
        <form class="form-horizontal" method="POST" action="/login.html" novalidate>
            {% csrf_token %}
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Username</label>
            <div class="col-sm-10">
              {{ obj.username }}
            </div>{{ obj.errors.username.0 }}
        </div>
      <div class="form-group">
        <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
        <div class="col-sm-10">
          {{ obj.password }}
        </div>{{ obj.errors.password.0 }}
      </div>
     <div class="form-group">
        <label class="col-sm-2 control-label">验证码</label>
        <div class="col-sm-5">
          <input type="text" class="form-control"  placeholder="验证码" name="code">
        </div>
        <div class="col-sm-5">
          <img style="width: 120px;height: 30px;" src="/check_code/">
        </div><span style="color: red"> {{ msg }}</span>
      </div>
      <div class="form-group">
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                  <input type="checkbox" id="rem"> Remember me
                    <input type="text" value="{{ url }}" name="url" style="display: none">
                </label>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
               <input type="submit" value="Sign in" class="btn btn-default">
            </div>
            </div>
      </div>
        </form>
        </div>
    </div>

</body>
</html>

templates/sign.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>帐号注册</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.css">
    <style>
        .outer{
            position: fixed;
            top: 50px;
            left: 50%;
            width: 800px;
            margin-left: -350px;
{#            border: 1px solid red;#}
        }
        .outer h2{
            margin-left: 250px;
            margin-bottom: 50px;
        }

    </style>
</head>
<body>
    <div class="outer">
        <h2>用户注册</h2>
        <form class="form-horizontal" method="POST" action="/reg.html" id="f1" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">用户名</label>
            <div class="col-sm-6">
              {{ obj.username }}
            </div>
              {{ obj.errors.username.0 }}
          </div>
          <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">邮箱</label>
            <div class="col-sm-6">
              {{ obj.email }}
            </div>{{ obj.errors.email.0 }}
          </div>
           <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">昵称</label>
            <div class="col-sm-6">
              {{ obj.nickname }}
            </div>{{ obj.errors.nickname.0 }}
          </div>
          <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">密码</label>
            <div class="col-sm-6">
              {{ obj.password }}
            </div>{{ obj.errors.password.0 }}
          </div>
          <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">确认密码</label>
            <div class="col-sm-6">
              {{ obj.pwd_again }}
            </div>{{ obj.errors.pwd_again.0 }}<span id="msg"></span>
          </div>
            <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">上传头像</label>
            <div class="col-sm-3">
              {{ obj.avatar }}
            </div>{{ obj.errors.avatar.0 }}
          </div>
            <div class="form-group" style="margin-top: 60px">
                <label class="col-sm-2 control-label">验证码</label>
                <div class="col-sm-3">
                  {{ obj.code }}
                </div>
                <div class="col-sm-5">
                  <img style="width: 120px;height: 30px;" src="/check_code/" id="img-code">
                </div><span style="color: red"> {{ obj.errors.code.0 }}</span>
            </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-6">
                <input type="submit" class="btn btn-default" value="提交">
            </div>
          </div>
        </form>
        <div style="position: absolute;margin-left: 17.2%;margin-top: -22.6%">
        <form action="/up_img/" method="POST" target="ifr" enctype="multipart/form-data" id="f2">
            {% csrf_token %}
             <iframe name="ifr" id="ifr" style="display: none">
            </iframe>
            <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label"></label>
            <div class="col-sm-6">
                <div style="z-index: 600;position: relative">
                    <img style="width: 80px;height: 80px;margin-top: -60%;margin-left: -100%" src="" id="show_img">
                </div>
                <div style="z-index: 800;position: relative;opacity: 0">
                    <input type="file" style="width: 80px;height: 80px;margin-top: -200%;margin-left: -100%" id="up-img" name="avatar">
                </div>
            </div>{{ obj.errors.pwd_again.0 }}<span id="msg"></span></div>
         </form>
        </div>
    </div>

    <script type="text/javascript" src="/static/jquery-3.2.1.js"></script>
    <script>
        $('#up-img').change(function () {
            document.getElementById("ifr").onload=loadIframe;
            $('#f2')[0].submit()
        });
        function loadIframe() {
            var content = document.getElementById('ifr').contentWindow.document.body.innerText;
            $('#show_img').attr('src',content);
            $('#id_avatar').val(content)
        }
        $('#img-code').click(function () {
            $(this).attr('src',$(this).attr('src')+'?')
        })

    </script>

</body>
</html>